version: '3'

services:
  apps:
    build:
      context: docker/apps
    env_file:
      - dev.env
    volumes:
      - ./phpfpm/dev/env.conf:/opt/bitnami/php/etc/php-fpm.d/env.conf
      - ./phpfpm/dev/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
      - ./phpfpm/logs:/var/log/php-fpm/
      - ./apps:/app

  caddy:
    image: caddy:2.4.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/dev/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/ssl
      - ./apps:/app
      - caddy_data:/data
    depends_on:
      - apps

  redis:
    image: redis:alpine


volumes:
  caddy_data:
