version: '3'

services:
  apps:
    build:
      context: docker/apps
    restart: always
    env_file:
      - prod.env
    volumes:
      - ./phpfpm/prod/env.conf:/opt/bitnami/php/etc/php-fpm.d/env.conf
      - ./phpfpm/prod/custom.ini:/opt/bitnami/php/etc/conf.d/custom.ini
      - ./apps:/app

  caddy:
    image: caddy:2.4.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/ssl
      - ./apps:/app
      - caddy_data:/data
    depends_on:
      - apps

  redis:
    image: redis:alpine

volumes:
  caddy_data:
